BEGIN;

CREATE SEQUENCE HIBERNATE_SEQUENCE;





CREATE TABLE PROVIDER (
	PROVIDER_NO VARCHAR(10) NOT NULL,
	CONSTRAINT PROVIDER_PK PRIMARY KEY (PROVIDER_NO),
	LAST_NAME VARCHAR(30) NOT NULL,
	FIRST_NAME VARCHAR(30) NOT NULL,
	PROVIDER_TYPE VARCHAR(15) NOT NULL,
	SPECIALTY VARCHAR(20) NOT NULL,
	TEAM VARCHAR(20),
	SEX CHAR(1) NOT NULL,
	DOB DATE,
	ADDRESS VARCHAR(40),
	PHONE VARCHAR(20),
	WORK_PHONE VARCHAR(50),
	OHIP_NO VARCHAR(20),
	RMA_NO VARCHAR(20),
	BILLING_NO VARCHAR(20),
	HSO_NO VARCHAR(10),
	STATUS CHAR(1),
	COMMENTS CLOB,
	PROVIDER_ACTIVITY CHAR(3)
);

INSERT INTO PROVIDER VALUES ('999997','oscaradmin','admin','admin',' ',' ',' ','01-JAN-0001',' ',' ',' ',' ',' ',' ',' ','1',' ',' ');
INSERT INTO PROVIDER VALUES ('999998','oscardoc','doctor','doctor',' ',' ',' ','01-JAN-0001',' ',' ',' ',' ',' ',' ',' ','1',' ',' ');
INSERT INTO PROVIDER VALUES ('999999','oscarrep','receptionist','receptionist',' ',' ',' ','01-JAN-0001',' ',' ',' ',' ',' ',' ',' ','1',' ',' ');
INSERT INTO PROVIDER VALUES ('88888','Support','IT','receptionist',' ','Admin',' ','01-JAN-0001',' ',' ',' ',' ',' ',' ',' ','1',' ',' ');
INSERT INTO PROVIDER VALUES ('174','Chan','David','doctor','Family Medicine','TEAM A','M','01-JAN-0001',' ','H 905-','058081',' ',' ','BAAP','1','1',' ',' ');





CREATE TABLE SECURITY (
	SECURITY_NO NUMBER(10) NOT NULL,
	CONSTRAINT SECURITY_PK PRIMARY KEY (SECURITY_NO),
	USER_NAME VARCHAR(30) NOT NULL,
	CONSTRAINT SECURITY_UK1 UNIQUE (USER_NAME),
	PASSWORD VARCHAR(80) NOT NULL,
	PROVIDER_NO VARCHAR(10),
	PIN VARCHAR(6),
	B_EXPIRESET NUMBER(1) DEFAULT 1,
	DATE_EXPIREDATE DATE DEFAULT '01-JAN-2100',
	B_LOCALLOCKSET NUMBER(1) DEFAULT 1,
	B_REMOTELOCKSET NUMBER(1) DEFAULT 1
);

INSERT INTO SECURITY VALUES (127,'oscarrep','-51-282443-97-5-9410489-60-1021-45-127-12435464-32','999999','1117',1,'01-JAN-3001',1,1);
INSERT INTO SECURITY VALUES (128,'oscardoc','-51-282443-97-5-9410489-60-1021-45-127-12435464-32','999998','1117',1,'01-JAN-3001',1,1);
INSERT INTO SECURITY VALUES (129,'oscaradmin','-51-282443-97-5-9410489-60-1021-45-127-12435464-32','999997','1117',1,'01-JAN-3001',1,1);





CREATE TABLE SECUSERROLE (
	PROVIDER_NO VARCHAR(10) NOT NULL,
	ROLE_NAME VARCHAR(30) NOT NULL,
	CONSTRAINT SECUSERROLE_PK PRIMARY KEY (PROVIDER_NO, ROLE_NAME)
);

INSERT INTO SECUSERROLE VALUES('999998', 'doctor');
INSERT INTO SECUSERROLE VALUES('999998', 'admin');
INSERT INTO SECUSERROLE VALUES('999997', 'receptionist');





CREATE TABLE LOG (
	DATETIME DATE,
	PROVIDER_NO VARCHAR(10) NOT NULL,
	CONSTRAINT LOG_PK PRIMARY KEY (DATETIME, PROVIDER_NO),
	ACTION VARCHAR(20),
	CONTENT VARCHAR(80) NOT NULL,
	CONTENTID VARCHAR(80),
	IP VARCHAR(30)
);

CREATE INDEX LOG_ACTION ON LOG(ACTION);
CREATE INDEX LOG_CONTENT ON LOG(CONTENT);
CREATE INDEX LOG_CONTENTID ON LOG(CONTENTID);





CREATE TABLE PREFERENCE (
	PREFERENCE_NO NUMBER(10) NOT NULL,
	CONSTRAINT PREFERENCE_PK PRIMARY KEY (PREFERENCE_NO),
	PROVIDER_NO VARCHAR(10) NOT NULL,
	START_HOUR CHAR(2),
	END_HOUR CHAR(2),
	EVERY_MIN CHAR(3),
	MYGROUP_NO VARCHAR(10),
	COLOR_TEMPLATE VARCHAR(10),
	NEW_TICKLER_WARNING_WINDOW VARCHAR(10) NOT NULL,	
	DEFAULT_SERVICETYPE VARCHAR(10)
);

CREATE INDEX PREFERENCE_PROVIDER_NO ON PREFERENCE(PROVIDER_NO);

INSERT INTO PREFERENCE VALUES (138,'999998','8','18','15','.default','deepblue',' ','');





CREATE TABLE PROVIDER_DEFAULT_PROGRAM (
	ID NUMBER(10) NOT NULL,
	CONSTRAINT PROVIDER_DEFAULT_PROGRAM_PK PRIMARY KEY (ID),
	PROVIDER_NO VARCHAR(10) NOT NULL,
	PROGRAM_ID NUMBER(10) NOT NULL,
	SIGNNOTE NUMBER(1)
);





CREATE TABLE SECOBJPRIVILEGE (
	ROLEUSERGROUP VARCHAR(30) NOT NULL,
	OBJECTNAME VARCHAR(100) NOT NULL,
	CONSTRAINT SECOBJPRIVILEGE_PK PRIMARY KEY (ROLEUSERGROUP, OBJECTNAME),
	PRIVILEGE VARCHAR(100) NOT NULL,
	PRIORITY NUMBER(2),
	PROVIDER_NO VARCHAR(10)
);

INSERT INTO SECOBJPRIVILEGE VALUES('receptionist', '_appointment', '|*|', 0, '999998');
INSERT INTO SECOBJPRIVILEGE VALUES('receptionist', '_demographic', '|*|', 0, '999998');
INSERT INTO SECOBJPRIVILEGE VALUES('receptionist', '_billing', '|*|', 0, '999998');
INSERT INTO SECOBJPRIVILEGE VALUES('receptionist','_masterLink','|*|',0,999998);
INSERT INTO SECOBJPRIVILEGE VALUES('doctor', '_appointment', '|*|', 0, '999998');
INSERT INTO SECOBJPRIVILEGE VALUES('doctor', '_eChart', '|*|', 0, '999998');
INSERT INTO SECOBJPRIVILEGE VALUES('doctor', '_appointment.doctorLink', '|*|', 0, '999998');
INSERT INTO SECOBJPRIVILEGE VALUES('doctor', '_eChart.verifyButton', '|*|', 0, '999998');
INSERT INTO SECOBJPRIVILEGE VALUES('doctor', '_demographic', '|*|', 0, '999998');
INSERT INTO SECOBJPRIVILEGE VALUES('doctor', '_billing', '|*|', 0, '999998');
INSERT INTO SECOBJPRIVILEGE VALUES('doctor', '_tasks', '|*|', 0, '999998');
INSERT INTO SECOBJPRIVILEGE VALUES('doctor','_masterLink','|*|',0,999998);
INSERT INTO SECOBJPRIVILEGE VALUES('doctor','_rx','|*|',0,999998);
INSERT INTO SECOBJPRIVILEGE VALUES('admin', '_admin', '|*|', 0, '999998');
INSERT INTO SECOBJPRIVILEGE VALUES('admin','_masterLink','|*|',0,999998);





CREATE TABLE PROGRAM_PROVIDER (
	ID NUMBER(10) NOT NULL,
	CONSTRAINT PROGRAM_PROVIDER_PK PRIMARY KEY (ID),
	PROGRAM_ID NUMBER(10),
	PROVIDER_NO NUMBER(10),
	ROLE_ID NUMBER(10),
	TEAM_ID NUMBER(10)
);

CREATE INDEX PROGRAM_PROVIDER_ROLE_ID ON PROGRAM_PROVIDER(ROLE_ID);
CREATE INDEX PROGRAM_PROVIDER_PROVIDER_NO ON PROGRAM_PROVIDER(PROVIDER_NO);
CREATE INDEX PROGRAM_PROVIDER_TEAM_ID ON PROGRAM_PROVIDER(TEAM_ID);





CREATE TABLE PROGRAM (
	PROGRAM_ID NUMBER(10) NOT NULL,
	CONSTRAINT PROGRAM_PK PRIMARY KEY (PROGRAM_ID),
	AGENCY_ID NUMBER(10) NOT NULL,
	INTAKE_PROGRAM NUMBER(10),
	NAME VARCHAR(70) NOT NULL,
	DESCR VARCHAR(255),
	ADDRESS VARCHAR(255) NOT NULL,
	PHONE VARCHAR(255) NOT NULL,
	FAX VARCHAR(255) NOT NULL,
	URL VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	EMERGENCY_NUMBER VARCHAR(255) NOT NULL,
	TYPE VARCHAR(50),
	LOCATION VARCHAR(70),
	MAX_ALLOWED NUMBER(6) NOT NULL,
	NUM_OF_MEMBERS NUMBER(6) NOT NULL,
	HOLDING_TANK NUMBER(1) NOT NULL,
	ALLOW_BATCH_ADMISSION NUMBER(1),
	ALLOW_BATCH_DISCHARGE NUMBER(1),
	HIC NUMBER(1),
	PROGRAM_STATUS VARCHAR(8) NOT NULL,
	BED_PROGRAM_LINK_ID NUMBER(10),
	MANORWOMAN VARCHAR(6),
	TRANSGENDER NUMBER(1),
	FIRSTNATION NUMBER(1),
	BEDPROGRAMAFFILIATED NUMBER(1),
	ALCOHOL NUMBER(1),
	ABSTINENCESUPPORT VARCHAR(20),
	PHYSICALHEALTH NUMBER(1),
	MENTALHEALTH NUMBER(1),
	HOUSING NUMBER(1),
	EXCLUSIVE_VIEW VARCHAR(20) NOT NULL
);

INSERT INTO PROGRAM (PROGRAM_ID,AGENCY_ID,NAME,DESCR,ADDRESS,PHONE,FAX,URL,EMAIL,EMERGENCY_NUMBER,TYPE,LOCATION,MAX_ALLOWED,NUM_OF_MEMBERS,HOLDING_TANK,ALLOW_BATCH_ADMISSION,ALLOW_BATCH_DISCHARGE,HIC, PROGRAM_STATUS,EXCLUSIVE_VIEW) VALUES (10001,0,'Subsidized Housing','Subsidized Housing',' ',' ',' ',' ',' ',' ','community',' ',99999,0,0,0,0,0,'active','no');
INSERT INTO PROGRAM (PROGRAM_ID,AGENCY_ID,NAME,DESCR,ADDRESS,PHONE,FAX,URL,EMAIL,EMERGENCY_NUMBER,TYPE,LOCATION,MAX_ALLOWED,NUM_OF_MEMBERS,HOLDING_TANK,ALLOW_BATCH_ADMISSION,ALLOW_BATCH_DISCHARGE,HIC, PROGRAM_STATUS,EXCLUSIVE_VIEW) VALUES (10002,0,'Private Market Housing','Private Market Housing',' ',' ',' ',' ',' ',' ','community',' ',99999,0,0,0,0,0,'active','no');
INSERT INTO PROGRAM (PROGRAM_ID,AGENCY_ID,NAME,DESCR,ADDRESS,PHONE,FAX,URL,EMAIL,EMERGENCY_NUMBER,TYPE,LOCATION,MAX_ALLOWED,NUM_OF_MEMBERS,HOLDING_TANK,ALLOW_BATCH_ADMISSION,ALLOW_BATCH_DISCHARGE,HIC, PROGRAM_STATUS,EXCLUSIVE_VIEW) VALUES (10003,0,'Returned to Previous Address','Returned to Previous Address',' ',' ',' ',' ',' ',' ','community',' ',99999,0,0,0,0,0,'active','no');
INSERT INTO PROGRAM (PROGRAM_ID,AGENCY_ID,NAME,DESCR,ADDRESS,PHONE,FAX,URL,EMAIL,EMERGENCY_NUMBER,TYPE,LOCATION,MAX_ALLOWED,NUM_OF_MEMBERS,HOLDING_TANK,ALLOW_BATCH_ADMISSION,ALLOW_BATCH_DISCHARGE,HIC, PROGRAM_STATUS,EXCLUSIVE_VIEW) VALUES (10004,0,'Returned To Partner','Returned To Partner',' ',' ',' ',' ',' ',' ','community',' ',99999,0,0,0,0,0,'active','no');
INSERT INTO PROGRAM (PROGRAM_ID,AGENCY_ID,NAME,DESCR,ADDRESS,PHONE,FAX,URL,EMAIL,EMERGENCY_NUMBER,TYPE,LOCATION,MAX_ALLOWED,NUM_OF_MEMBERS,HOLDING_TANK,ALLOW_BATCH_ADMISSION,ALLOW_BATCH_DISCHARGE,HIC, PROGRAM_STATUS,EXCLUSIVE_VIEW) VALUES (10005,0,'Returned to Parents','Returned to Parents',' ',' ',' ',' ',' ',' ','community',' ',99999,0,0,0,0,0,'active','no');
INSERT INTO PROGRAM (PROGRAM_ID,AGENCY_ID,NAME,DESCR,ADDRESS,PHONE,FAX,URL,EMAIL,EMERGENCY_NUMBER,TYPE,LOCATION,MAX_ALLOWED,NUM_OF_MEMBERS,HOLDING_TANK,ALLOW_BATCH_ADMISSION,ALLOW_BATCH_DISCHARGE,HIC, PROGRAM_STATUS,EXCLUSIVE_VIEW) VALUES (10006,0,'Moved in with Friends or Relatives','Moved in with Friends or Relatives',' ',' ',' ',' ',' ',' ','community',' ',99999,0,0,0,0,0,'active','no');
INSERT INTO PROGRAM (PROGRAM_ID,AGENCY_ID,NAME,DESCR,ADDRESS,PHONE,FAX,URL,EMAIL,EMERGENCY_NUMBER,TYPE,LOCATION,MAX_ALLOWED,NUM_OF_MEMBERS,HOLDING_TANK,ALLOW_BATCH_ADMISSION,ALLOW_BATCH_DISCHARGE,HIC, PROGRAM_STATUS,EXCLUSIVE_VIEW) VALUES (10007,0,'Continued at Another Hospital or Treatment','Continued at Another Hospital or Treatment',' ',' ',' ',' ',' ',' ','community',' ',99999,0,0,0,0,0,'active','no');
INSERT INTO PROGRAM (PROGRAM_ID,AGENCY_ID,NAME,DESCR,ADDRESS,PHONE,FAX,URL,EMAIL,EMERGENCY_NUMBER,TYPE,LOCATION,MAX_ALLOWED,NUM_OF_MEMBERS,HOLDING_TANK,ALLOW_BATCH_ADMISSION,ALLOW_BATCH_DISCHARGE,HIC, PROGRAM_STATUS,EXCLUSIVE_VIEW) VALUES (10008,0,'Left the City','Left the City',' ',' ',' ',' ',' ',' ','community',' ',99999,0,0,0,0,0,'active','no');
INSERT INTO PROGRAM (PROGRAM_ID,AGENCY_ID,NAME,DESCR,ADDRESS,PHONE,FAX,URL,EMAIL,EMERGENCY_NUMBER,TYPE,LOCATION,MAX_ALLOWED,NUM_OF_MEMBERS,HOLDING_TANK,ALLOW_BATCH_ADMISSION,ALLOW_BATCH_DISCHARGE,HIC, PROGRAM_STATUS,EXCLUSIVE_VIEW) VALUES (10009,0,'Whereabouts Unknown (AWOL)','Whereabouts Unknown (AWOL)',' ',' ',' ',' ',' ',' ','community',' ',99999,0,0,0,0,0,'active','no');
INSERT INTO PROGRAM (PROGRAM_ID,AGENCY_ID,NAME,DESCR,ADDRESS,PHONE,FAX,URL,EMAIL,EMERGENCY_NUMBER,TYPE,LOCATION,MAX_ALLOWED,NUM_OF_MEMBERS,HOLDING_TANK,ALLOW_BATCH_ADMISSION,ALLOW_BATCH_DISCHARGE,HIC, PROGRAM_STATUS,EXCLUSIVE_VIEW) VALUES (10010,0,'Community, unknown destination','Community, unknown destination',' ',' ',' ',' ',' ',' ','community',' ',99999,0,0,0,0,0,'active','no');
INSERT INTO PROGRAM (PROGRAM_ID,AGENCY_ID,NAME,DESCR,ADDRESS,PHONE,FAX,URL,EMAIL,EMERGENCY_NUMBER,TYPE,LOCATION,MAX_ALLOWED,NUM_OF_MEMBERS,HOLDING_TANK,ALLOW_BATCH_ADMISSION,ALLOW_BATCH_DISCHARGE,HIC, PROGRAM_STATUS,EXCLUSIVE_VIEW) VALUES (10011,0,'Incarcerated','Incarcerated',' ',' ',' ',' ',' ',' ','community',' ',99999,0,0,0,0,0,'active','no');
INSERT INTO PROGRAM (PROGRAM_ID,AGENCY_ID,NAME,DESCR,ADDRESS,PHONE,FAX,URL,EMAIL,EMERGENCY_NUMBER,TYPE,LOCATION,MAX_ALLOWED,NUM_OF_MEMBERS,HOLDING_TANK,ALLOW_BATCH_ADMISSION,ALLOW_BATCH_DISCHARGE,HIC, PROGRAM_STATUS,EXCLUSIVE_VIEW) VALUES (10012,0,'Deceased','Deceased',' ',' ',' ',' ',' ',' ','community',' ',99999,0,0,0,0,0,'active','no');
INSERT INTO PROGRAM (PROGRAM_ID,AGENCY_ID,NAME,DESCR,ADDRESS,PHONE,FAX,URL,EMAIL,EMERGENCY_NUMBER,TYPE,LOCATION,MAX_ALLOWED,NUM_OF_MEMBERS,HOLDING_TANK,ALLOW_BATCH_ADMISSION,ALLOW_BATCH_DISCHARGE,HIC, PROGRAM_STATUS,EXCLUSIVE_VIEW) VALUES (10013,0,'Community Shelter','Community Shelter',' ',' ',' ',' ',' ',' ','community',' ',99999,0,0,0,0,0,'active','no');
INSERT INTO PROGRAM (PROGRAM_ID,AGENCY_ID,NAME,DESCR,ADDRESS,PHONE,FAX,URL,EMAIL,EMERGENCY_NUMBER,TYPE,LOCATION,MAX_ALLOWED,NUM_OF_MEMBERS,HOLDING_TANK,ALLOW_BATCH_ADMISSION,ALLOW_BATCH_DISCHARGE,HIC, PROGRAM_STATUS,EXCLUSIVE_VIEW) VALUES (10014,0,'Other','Other',' ',' ',' ',' ',' ',' ','community',' ',99999,0,0,0,0,0,'active','no');





CREATE TABLE DEMOGRAPHIC ( 
	DEMOGRAPHIC_NO NUMBER(10) NOT NULL,
	CONSTRAINT DEMOGRAPHIC_PK PRIMARY KEY (DEMOGRAPHIC_NO),
	LAST_NAME VARCHAR(30) NOT NULL,
	FIRST_NAME VARCHAR(30) NOT NULL,
	ADDRESS VARCHAR(60),
	CITY VARCHAR(20),
	PROVINCE VARCHAR(20),
	POSTAL VARCHAR(9),
	PHONE VARCHAR(20),
	PHONE2 VARCHAR(20),
	EMAIL VARCHAR(100),
	PIN VARCHAR(255),
	YEAR_OF_BIRTH VARCHAR(4),
	MONTH_OF_BIRTH CHAR(2),
	DATE_OF_BIRTH CHAR(2),
	HIN VARCHAR(20),
	VER CHAR(3),
	ROSTER_STATUS VARCHAR(20),
	PATIENT_STATUS VARCHAR(20),
	DATE_JOINED DATE,
	CHART_NO VARCHAR(10),
	PROVIDER_NO VARCHAR(250),
	SEX CHAR(1) NOT NULL,
	END_DATE DATE,
	EFF_DATE DATE,
	PCN_INDICATOR VARCHAR(20),
	HC_TYPE VARCHAR(20),
	HC_RENEW_DATE DATE,
	FAMILY_DOCTOR VARCHAR(80)
);

CREATE INDEX DEMOGRAPHIC_HIN ON DEMOGRAPHIC(HIN);
CREATE INDEX DEMOGRAPHIC_NAME ON DEMOGRAPHIC(LAST_NAME, FIRST_NAME);





CREATE TABLE ADMISSION (
	AM_ID NUMBER(10) NOT NULL,
	CONSTRAINT ADMISSION_PK PRIMARY KEY (AM_ID),
	CLIENT_ID NUMBER(10) NOT NULL,
	PROGRAM_ID NUMBER(10) NOT NULL,
	PROVIDER_NO NUMBER(10) NOT NULL,
	ADMISSION_DATE DATE,
	ADMISSION_NOTES VARCHAR(255),
	TEMP_ADMISSION CHAR(1),
	DISCHARGE_DATE DATE,
	DISCHARGE_NOTES VARCHAR(255),
	TEMP_ADMIT_DISCHARGE CHAR(1),
	ADMISSION_STATUS VARCHAR(24),
	TEAM_ID NUMBER(10),
	TEMPORARY_ADMISSION_FLAG NUMBER(1),
	AGENCY_ID NUMBER(11),
	RADIODISCHARGEREASON VARCHAR(10),
	CLIENTSTATUS_ID NUMBER(20)
);

CREATE INDEX ADMISSION_TEAM_ID ON ADMISSION(TEAM_ID);





CREATE TABLE PROPERTY (
	NAME VARCHAR(255) NOT NULL,
	VALUE VARCHAR(255),
	ID NUMBER(10) NOT NULL,
	CONSTRAINT PROPERTY_PK PRIMARY KEY (ID),
	PROVIDER_NO VARCHAR(10)
);





CREATE TABLE SYSTEM_MESSAGE (
	ID NUMBER(10) NOT NULL,
	CONSTRAINT SYSTEM_MESSAGE_PK PRIMARY KEY (ID),
	MESSAGE CLOB NOT NULL,
	CREATION_DATE DATE NOT NULL,
	EXPIRY_DATE DATE NOT NULL
);





CREATE TABLE MYGROUP (
	MYGROUP_NO VARCHAR(10) NOT NULL,
	PROVIDER_NO VARCHAR(10) NOT NULL,
	CONSTRAINT MYGROUP_PK PRIMARY KEY (MYGROUP_NO,PROVIDER_NO),
	LAST_NAME VARCHAR(30) NOT NULL,
	FIRST_NAME VARCHAR(30) NOT NULL,
	VIEWORDER CHAR(2)
);





CREATE TABLE SCHEDULEDATE (
	ID NUMBER(6) NOT NULL,
	CONSTRAINT SCHEDULEDATE_PK PRIMARY KEY (ID),
	SDATE DATE NOT NULL,
	PROVIDER_NO VARCHAR(6) NOT NULL,
	AVAILABLE CHAR(1) NOT NULL,
	PRIORITY CHAR(1),
	REASON VARCHAR(255),
	HOUR VARCHAR(255),
	CREATOR VARCHAR(50),
	STATUS CHAR(1) NOT NULL
);





CREATE TABLE AGENCY (
	ID NUMBER(10) NOT NULL,
	CONSTRAINT AGENCY_PK PRIMARY KEY (ID),
	INTAKE_QUICK NUMBER(10) NOT NULL,
	INTAKE_QUICK_STATE CHAR(2) NOT NULL,
	INTAKE_INDEPTH NUMBER(10),
	INTAKE_INDEPTH_STATE CHAR(2) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(255),
	CONTACT_NAME VARCHAR(255),
	CONTACT_EMAIL VARCHAR(255),
	CONTACT_PHONE VARCHAR(255),
	LOCAL NUMBER(1) NOT NULL,
	INTEGRATOR_ENABLED NUMBER(1) NOT NULL,
	INTEGRATOR_URL VARCHAR(255),
	INTEGRATOR_JMS VARCHAR(255),
	INTEGRATOR_USERNAME VARCHAR(255),
	INTEGRATOR_PASSWORD VARCHAR(255),
	HIC NUMBER(1),
	DISABLED NUMBER(1) NOT NULL
);





CREATE TABLE SCHEDULETEMPLATE (
	PROVIDER_NO VARCHAR(10) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	CONSTRAINT SCHEDULETEMPLATE_PK PRIMARY KEY (PROVIDER_NO,NAME),
	SUMMARY VARCHAR(80),
	TIMECODE VARCHAR(255)
);





CREATE TABLE SCHEDULETEMPLATECODE (
	CODE CHAR(1) NOT NULL,
	DESCRIPTION VARCHAR(80),
	DURATION CHAR(3),
	COLOR VARCHAR(10),
	CONFIRM CHAR(3) NOT NULL
);

CREATE INDEX SCHEDULETEMPLATECODE_CODE ON SCHEDULETEMPLATECODE(CODE);

INSERT INTO SCHEDULETEMPLATECODE VALUES ('A','Academic','',NULL,'N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('B','Behavioral Science','15','#BFEFFF','N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('2','30 Minute Appointment','30','#BFEFFF','N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('3','45 Minute Appointment','45','#BFEFFF','N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('P','Phone time','15','#BFEFFF','N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('M','Monitoring','','EED2EE','N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('6','60 Minute Appointment','60','#BFEFFF','N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('C','Chart Audit Rounds','15',NULL,'N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('R','Rounds','15',NULL,'N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('E','Study Leave','15',NULL,'N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('V','Vacation','15','FFF68F','N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('G','PBSG Rounds','15',NULL,'N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('H','Hospital Rounds','15',NULL,'N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('d','Drug Rep (Chief)','15',NULL,'N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('U','Urgent','15',NULL,'N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('a','Administrative Work','15','#BFEFFF','N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('t','Travel','',NULL,'N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('m','Meeting','',NULL,'N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('1','15 Minute Appointment','15','#BFEFFF','N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('s','Same Day','15','FFF68F','N');
INSERT INTO SCHEDULETEMPLATECODE VALUES ('S','Same Day - R1','30','FFF68F','N');





CREATE TABLE PROVIDERLABROUTING (
	PROVIDER_NO VARCHAR(10) NOT NULL,
	LAB_NO NUMBER(10) NOT NULL,
	STATUS CHAR(1),
	COMMENT1 VARCHAR(255),
	TIMESTAMP DATE NOT NULL,
	LAB_TYPE CHAR(3),
	ID NUMBER(10) NOT NULL,
	CONSTRAINT PROVIDERLABROUTING_PK PRIMARY KEY (ID)
);





CREATE TABLE MESSAGELISTTBL (
	MESSAGE NUMBER(10),
	PROVIDER_NO VARCHAR(10),
	STATUS VARCHAR(10),
	REMOTELOCATION NUMBER(10)
);





CREATE TABLE OSCARCOMMLOCATIONS (
	LOCATIONID NUMBER(10) NOT NULL,
	CONSTRAINT OSCARCOMMLOCATIONS_PK PRIMARY KEY (LOCATIONID),
	LOCATIONDESC VARCHAR(50) NOT NULL,
	LOCATIONAUTH VARCHAR(30),
	CURRENT1 NUMBER(1) NOT NULL,
	ADDRESSBOOK CLOB,
	REMOTESERVERURL VARCHAR(30)
);





CREATE TABLE TICKLER (
	TICKLER_NO NUMBER(10) NOT NULL,
	CONSTRAINT TICKLER_PK PRIMARY KEY (TICKLER_NO),
	DEMOGRAPHIC_NO NUMBER(10),
	MESSAGE CLOB,
	STATUS CHAR(1),
	UPDATE_DATE DATE,
	SERVICE_DATE DATE,
	CREATOR VARCHAR(10),
	PRIORITY VARCHAR(6),
	TASK_ASSIGNED_TO VARCHAR(255)
);





CREATE TABLE SCRATCH_PAD (
	ID NUMBER(10) NOT NULL,
	CONSTRAINT SCRATCH_PAD_PK PRIMARY KEY (ID),
	PROVIDER_NO VARCHAR(10),
	DATE_TIME DATE,
	SCRATCH_TEXT CLOB
);



COMMIT;

