{
   "generalInfo":[
      {
         "firstName":"John",
         "lastName":"Doe",
         "age":25
      },
      {
         "firstName":"John1",
         "lastName":"Doe",
         "age":25
      },
      {
         "firstName":"John2",
         "lastName":"Doe",
         "age":25
      },
      {
         "firstName":"John3",
         "lastName":"Doe",
         "age":25
      },
      {
         "firstName":"John4",
         "lastName":"Doe",
         "age":25
      },
      {
         "firstName":"John5",
         "lastName":"Doe",
         "age":25
      }
   ],
   "appointmentType":[
      {
         "id":"E",
         "val":"E-chart"
      },
      {
         "id":"I",
         "val":"Intake form"
      },
      {
         "id":"B",
         "val":"Billing"
      },
      {
         "id":"RX",
         "val":"RX"
      }
   ],
   "appointmentStatus":[
      {
         "id":"TD",
         "val":"To do"
      },
      {
         "id":"DP",
         "val":"Daysheet printed"
      },
      {
         "id":"HR",
         "val":"Here"
      },
      {
         "id":"EM",
         "val":"Empty room"
      },
      {
         "id":"NS",
         "val":"No show"
      },
      {
         "id":"CX",
         "val":"Cancelled"
      },
      {
         "id":"NP",
         "val":"Ready for NP"
      },
      {
         "id":"FT",
         "val":"Fast track"
      }
   ],
   "appTime":[
      {
         "id":"8",
         "val":"08:00"
      },
      {
         "id":"9",
         "val":"09:00"
      },
      {
         "id":"10",
         "val":"10:00"
      },
      {
         "id":"11",
         "val":"11:00"
      },
      {
         "id":"12",
         "val":"12:00"
      },
      {
         "id":"13",
         "val":"13:00"
      },
      {
         "id":"14",
         "val":"14:00"
      },
      {
         "id":"15",
         "val":"15:00"
      },
      {
         "id":"16",
         "val":"16:00"
      },
      {
         "id":"17",
         "val":"17:00"
      },
      {
         "id":"18",
         "val":"18:00"
      },
      {
         "id":"19",
         "val":"19:00"
      },
      {
         "id":"20",
         "val":"20:00"
      },
      {
         "id":"21",
         "val":"21:00"
      },
      {
         "id":"22",
         "val":"22:00"
      }
   ]
}