CREATE TABLE `consultationreport` (
  `date` date DEFAULT NULL,
  `request_id` int(10) NOT NULL AUTO_INCREMENT,
  `referal_id` int(10) DEFAULT NULL,
  `appointmentNo` int(12) DEFAULT '0',
  `appointment_date` date DEFAULT NULL,
  `appointment_time` time DEFAULT NULL,
  `cc_text` text,
  `reason` text,
  `clinical_info` text,
  `current_meds` text,
  `allergies` text,
  `provider` varchar(60) DEFAULT NULL,
  `demographicNo` int(10) DEFAULT NULL,
  `status` varchar(2) DEFAULT NULL,
  `status_text` text,
  `sendto` varchar(20) DEFAULT NULL,
  `examination` text,
  `concurrentproblems` text,
  `impression` text,
  `plan` text,
  `con_type` varchar(5) DEFAULT '',
  `con_memo` text,
  `urgency` varchar(2) DEFAULT NULL,
  `patient_will_book` tinyint(1) DEFAULT NULL,
  `greeting` int(11) DEFAULT '1',
  PRIMARY KEY (`request_id`),
  KEY `date` (`date`)
);

